### DISCUSSION TITLE
Export do influxdb lub mqtt ?

### DISCUSSION THREAD

**Discussion by mmg1t** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#108] [Ideas]
Zastanawiam się jak rysować wykresy z wartości prezentowanych z tej integracji.
Wykresy w samym home assistant sa dość ubogie w funkcjonlanosci wiec myśle tutaj o Grafanie (również posiadam),
z tym że datasource byloby dobrze mieć zewnętrzne w postaci InfluxDB, czy też MQTT, albo Prometheus. ?

Co myślicie o tym ?

Ew. gdzie w kodzie najlepiej byłoby się wpiąć by esportować do w/w systemów ? (moge napisać coś, choć tak eleganckie to pewnie nie będzie ;-) )

PS.
dobrze byloby też mieć możliwość wyeksportowania danych historyczny prezentowanych w eliczniku do tegoż influxa, w internetach są gotowce konwertujące XLSa/CSV do influxa, ale może da się to zrobić jakoś przyjemnie w AMIplus ?

**Comment by PiotrMachowski** [comment]
Ta integracja zapisuje dane godzinowe bezpośrednio do bazy danych [tutaj](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/blob/master/custom_components/tauron_amiplus/statistics.py#L196).

Możesz ewentualnie spróbować pobawić się [tym skryptem](https://github.com/manio/elicznik-rs) - importuje on dane do bazy PostgreSQL

W sumie, to najbardziej odpornym rozwiązaniem chyba by było pobieranie danych z bazy HA i wrzucanie ich do Influxa

**Reply by mmg1t** [reply]
> tutaj 

o, super, dokladnie o tym myslalem :)

>tym skryptem

ciekawe, wyglada calkiem dobrze, dzieki :)

> odpornym(..)influxa

tak, wlasnie proboje to zrobic, wygląda na to że homeassistant potrafi pisac do influxa stany encji,
... oraz w druga strone - uzywać ich do sensorów:) wyglada b.interesująco

doc: https://www.home-assistant.io/integrations/influxdb

**Reply by PiotrMachowski** [reply]
> homeassistant potrafi pisac do influxa stany encji,

taaaak, ale dane godzinne nie są zapisywane jako encja, tylko bezpośrednio jako statystyki. Może dla nich też działa, ale musiałbyś spróbować

**Comment by mmg1t** [comment]
wyglada na to ze dziala :)

gotowiec z https://www.home-assistant.io/integrations/influxdb
influxdb:  
  api_version: 2
(...)


Flex query w Grafanie, czary mary i sa wszystkie wartosci (po dwie, bo restartowalem wiec wczytalo to samo):

from(bucket: "BUCKET_NAME")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r.entity_id =~ /tauron/ )
  |> filter(fn: (r) => r["_measurement"] == "kWh")
  |> filter(fn: (r) => r["_field"] == "value")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")

**Reply by PiotrMachowski** [reply]
Ale godzinnych odczytów to chyba nie zaczytało?

**Reply by mmg1t** [reply]
godzinne ? co to ?
to są jeszcze jakies inne poza tymi?

---w integracji mam tylko takie:
Tauron AMIplus [1 device] and [16 entities]

daszboard:
```yaml
entities:
  - entity: sensor.tauron_amiplus_59*****_configurable_balance
  - entity: sensor.tauron_amiplus_59*****_configurable_energy_consumption
  - entity: sensor.tauron_amiplus_59*****_configurable_energy_generation
  - entity: sensor.tauron_amiplus_59*****_current_consumption_reading
  - entity: sensor.tauron_amiplus_59*****_current_generation_reading
  - entity: sensor.tauron_amiplus_59*****_daily_balance
  - entity: sensor.tauron_amiplus_59*****_daily_energy_consumption
  - entity: sensor.tauron_amiplus_59*****_daily_energy_generation
  - entity: sensor.tauron_amiplus_59*****_last_12_months_balance
  - entity: sensor.tauron_amiplus_59*****_last_12_months_energy_consumption
  - entity: sensor.tauron_amiplus_59*****_last_12_months_energy_generation
  - entity: sensor.tauron_amiplus_59*****_monthly_balance
  - entity: sensor.tauron_amiplus_59*****_monthly_energy_consumption
  - entity: sensor.tauron_amiplus_59*****_monthly_energy_generation
  - entity: sensor.tauron_amiplus_59*****_yearly_energy_consumption
  - entity: sensor.tauron_amiplus_59*****_yearly_energy_generation
```
