### DISCUSSION TITLE
Wykres generacji dziennej

### DISCUSSION THREAD

**Discussion by mattPiratt** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#111] [Q&A]
Czy mogę uzyskać dzięki tym sensorom, wykres słupkowy, z ostatnich 7 dni, ile było energii oddanej? 7 słupków = 7 dni.
Pozdrawiam i dziękuję

**Comment by PiotrMachowski** [comment]
Najłatwiej takie coś osiągniesz w panelu energia

**Comment by mattPiratt** [comment]
Tak, ta encja tauron_importer:..... poprawnie oddaje dane do panelu Energia.
Czy jednak można jakoś użyć jej do wygenerowanie "karty" z wykresem/chartem na dowolnym ekranie HA? Nie potrafię do tego dość. Może jakoś jako "sensor.tauron_importer:..." :)

Pozdrawiam

**Comment by PiotrMachowski** [comment]
Ok, da się to zrobić kartą statystyk:
```yaml
type: statistics-graph
chart_type: bar
period: day
days_to_show: 7
entities:
  - tauron_importer:123456789_consumption
stat_types:
  - state
```

**Reply by PiotrMachowski** [reply]
@mattPiratt proszę odpowiadaj w wątku.

Wygląda na to, że przy takiej konfiguracji wyświetlane są dane pierwszej godziny danego dnia. Możesz zrobić tak:
```yaml
type: statistics-graph
chart_type: bar
period: day
days_to_show: 8
entities:
  - tauron_importer:123456789_consumption
stat_types:
  - change
```
Wtedy pierwszy dzień będzie zawsze pusty, ale reszta będzie się zgadzać.
