### DISCUSSION TITLE
Jak obliczyć energię dostępną jako prosumenta

### DISCUSSION THREAD

**Discussion by aradiush** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#113] [Q&A]
Witam. Proszę o podpowiedź , do którego config-a dopisać podane wiersze

**Comment by PiotrMachowski** [comment]
Zakładam, że chodzi o konfigurację z [FAQ](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#faq). Trzeba ją dodać do pliku configuration.yaml

**Comment by aradiush** [comment]
Tak. Próbuję to dodać właśnie .

template: !include templates.yaml
input_number: !include input_numbers.yaml

**Reply by PiotrMachowski** [reply]
To wystarczy pominąć linijki `input_number:` i `template:`, a następnie umieścić odpowiednie części w odpowiadających plikach

**Comment by aradiush** [comment]
tak tak , zrobione . 
Mam jeszcze pytanie odnośnie zakładki Energia  , dodane mam encje importer a w danym dniu "nie może obliczyć neutralności sieci" oraz "Nie można obliczyć zużycia energii słonecznej na własne potrzeby" 
Tygodniowo, miesięcznie, rocznie, pokazuje elegancko

**Reply by PiotrMachowski** [reply]
Tych wartości HA nie jest w stanie obliczyć tylko na podstawie danych z Tauronu. Musisz wypełnić odpowiednie wartości przy konfiguracji panelu Energia

**Reply by mmarcines** [reply]
W https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#faq wzor na obliczenie zapasu dla prosumenta:
state: "{{ (states('input_number.initial_energy_bank') | float(0) + states('sensor.tauron_amiplus_123_yearly_energy_generation') | float(0) * 0.8 - states('sensor.tauron_amiplus_123_yearly_energy_consumption') | float(0)) | round(3) }}"

Aczkolwiek tauron_amiplus_123_yearly_energy_generation i tauron_amiplus_123_yearly_energy_consumption - nie sa wartosciami uwzgledniajacymi bilansowanie godzinowe. 

Czy daloby sie jakos w latwy sposob wykorzystac statystki z panelu energia ? Tam wartosci sa zbalansowane (i zgadzaja sie co do przecinka) - tylko brakuje sensora, ktory by dawal wartosc dla sensor.tauron_amiplus_123_configurable_balanced_consumption i tauron_amiplus_123_configurable_balanced_generation

**Reply by PiotrMachowski** [reply]
Nie da się w prosty sposób użyć danych z panelu Energia, ale te same dane są dostępne w odpowiednich sensorach: "Configurable balance", "Daily balance", "Monthly balance" i "Last 12 months balance". Stan tych sensorów to różnica między zbalansowanymi produkcją, a konsumpcją, ale w atrybutach są dostępne obie te wartości.

**Reply by mmarcines** [reply]
@PiotrMachowski  

takie cos mi wyszlo. 

Prosze o ew. sugestie/krytyke jesli cos mozna by bylo lepiej zrobic (ja mam instalacje <10kWp - wiec mam mnoznik 0.8).
```
- sensor:
    - name: "Tauron energy bank - balanced"
          unique_id: tauron_energy_bank_balanced
          icon: mdi:home-battery-outline
          unit_of_measurement: "kWh"
          state_class: total
          device_class: energy
          state: "{{ (states('input_number.initial_energy_bank') | float(0) + state_attr('sensor.tauron_amiplus_123_configurable_balance', 'sum_generation') | float(0) *(-0.8) - state_attr('sensor.tauron_amiplus_123_configurable_balance', 'sum_consumption') | float(0)) | round(2) }}"
          availability: "{{ states('sensor.tauron_amiplus_123_configurable_balance') | is_number }}"
```
