### ISSUE TITLE
encja: Tauron AMIplus 5xxxxxxxxxxxxxxxxx Current consumption reading

### ISSUE THREAD

**Issue by robertfili** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#145]
Jak w tytule wartość encji: nieznany

**Comment by PiotrMachowski** [comment]
1. Czy za wczoraj odczyty są widoczne na stronie?
2. Spróbuj wywołać taką usługę:
    ```yaml
    service: homeassistant.update_entity
    data:
      entity_id: sensor.tauron_amiplus_123456_current_consumption_reading
    ```
