### ISSUE TITLE
Invalid config for [sensor.template]: [state_class] is an invalid option for [sensor.template]. Check: sensor.template->sensors->tauron_bank_energii->state_class. (See ?, line ?).

### ISSUE THREAD

**Issue by lakusz1github** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#149]
Dodałem do configa HA, dane do wyliczania ile energi mam jeszcze w Tauronie, ale w Dev Toolsie mam taki błąd:

Invalid config for [sensor.template]: [state_class] is an invalid option for [sensor.template]. Check: sensor.template->sensors->tauron_bank_energii->state_class. (See ?, line ?).

Config wygląda tak:
```
  - platform: template
    sensors:
      tauron_bank_energii:
        state_class: total
        device_class: energy
        unique_id: tauron_energy_bank
        icon: mdi:home-battery-outline
        state: "{{ (states('input_number.initial_energy_bank') | float(0) + states('sensor.tauron_amiplus_123_yearly_energy_generation') | float(0) * 0.8 - states('sensor.tauron_amiplus_123_yearly_energy_consumption') | float(0)) | round(3) }}"
        unit_of_measurement: "kWh"
        availability: "{{ states('sensor.tauron_amiplus_123_yearly_energy_generation') | is_number and states('sensor.tauron_amiplus_123_yearly_energy_consumption') | is_number }}"
```
