### ISSUE TITLE
Propozycja: Dane po blilansowaniu

### ISSUE THREAD

**Issue by xtronets** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#178]
aby można było wyświetlać dane po bilansowaniu wektorowym

**Comment by PiotrMachowski** [comment]
Już można przecież

**Comment by xtronets** [comment]
w wypadku kiedy mam wybrany okres a nie rok kalendarzowy funkcja nie działa

**Comment by PiotrMachowski** [comment]
Nie do końca rozumiem, nie powinno być żadnej specjalnej różnicy

**Comment by PiotrMachowski** [comment]
Powinna być encja "Configurable balance"

**Comment by xtronets** [comment]
Tak mam taką encję , a nie można by zrobić dodatkowej encji dla poboru i generowania ale po bilansowaniu

**Comment by PiotrMachowski** [comment]
Te wartości są dostępne w atrybutach

**Comment by Landiss** [comment]
Mogę poprosić o dokładniejsze wyjaśnienia, bo nie wiem, gdzie te dane są. Albo czegoś nie rozumiem, albo wyżej doszło do jakiegoś nieporozumienia.

Przy wszystkich włączonych opcjach konfiguracji, urządzenie ma 17 sensorów i wszystkie zawierają dane bez zbilansowania godzinowego (po trzy, czyli pobór, oddanie i różnica, z danymi za ostatni dzień, miesiąc, rok, 12 miesięcy, konfigurowalny okres, do tego 2 sensory z aktualnym stanem licznika). Bilansowanie godzinowe mogę znaleźć wyłącznie w statystykach, jako importery, np.  tauron_importer:123456_balanced_consumption 

Nie widzę danych zbilansowanych w atrybutach sensorów, tutaj przykład z configurable consumption:

> state_class: total
tariff: G12W
sum_consumption: 299.36
sum_generation: -388.827
data_range: 2024-03-01 - 2024-03-30
poza szczytem_consumption: 173.832
szczyt_consumption: 125.528
szczyt_generation: -192.077
poza szczytem_generation: -196.75
unit_of_measurement: kWh
device_class: energy
icon: mdi:counter
friendly_name: Tauron AMIplus 123456 Configurable balance

Czy w związku z tym jest jakiś sposób, żeby sobie zaimplementować liczenie magazynu energii? Tauron liczy to według danych zbilansowanych godzinowo i dla konkretnego okresu rozliczeniowego. Kod podany w FAQ bierze to z danych surowych rocznych:

> input_number:
  initial_energy_bank:
    min: 0
    max: 100000000
    step: 1
    mode: box
template:
  - sensor:
      - name: Tauron energy bank
        state_class: total
        device_class: energy
        unique_id: tauron_energy_bank
        icon: mdi:home-battery-outline
        state: "{{ (states('input_number.initial_energy_bank') | float(0) + states('sensor.tauron_amiplus_123_yearly_energy_generation') | float(0) * 0.8 - states('sensor.tauron_amiplus_123_yearly_energy_consumption') | float(0)) | round(3) }}"
        unit_of_measurement: "kWh"
        availability: "{{ states('sensor.tauron_amiplus_123_yearly_energy_generation') | is_number and states('sensor.tauron_amiplus_123_yearly_energy_consumption') | is_number }}"

**Comment by PiotrMachowski** [comment]
> Nie widzę danych zbilansowanych w atrybutach sensorów, tutaj przykład z configurable consumption:
> 
> ```yaml
> state_class: total
> tariff: G12W
> sum_consumption: 299.36
> sum_generation: -388.827
> data_range: 2024-03-01 - 2024-03-30
> poza szczytem_consumption: 173.832
> szczyt_consumption: 125.528
> szczyt_generation: -192.077
> poza szczytem_generation: -196.75
> unit_of_measurement: kWh
> device_class: energy
> icon: mdi:counter
> friendly_name: Tauron AMIplus 123456 Configurable balance
> ```

Konkretne zbalansowane wartości zużycia/generacji są w atrybutach z końcówkami `_consumption` i `_generation`. Wartości `sum_consumption` i `sum_generation` są sumą dla wszystkich stref, reszta par jest dla konkretnych stref.

**Comment by Landiss** [comment]
Ach, dzięki! Byłem przekonany, że to są wartości bez zbilansowania, no bo nie mają w nazwie balanced, ale rzeczywiście masz rację.

**Comment by PiotrMachowski** [comment]
Cała encja jest balanced, nie chciałem powtarzać w każdym miejscu 😉

**Comment by Landiss** [comment]
Ok, jasne. Moja pomyłka wzięła się stąd, że myślałem, że nazwa encji odnosi się po prostu do faktu, że to generacja minus pobór (ponieważ siłą rzeczy wynik jest taki sam niezależnie, czy by to liczyć na danych zbilansowanych czy nie). Tak czy inaczej, udało mi się wszystko ustawić i mam poprawną wartość energii zmagazynowanej w sieci. Wielkie dzięki za pomoc i za samą integrację!

**Comment by Mice30** [comment]
> Ok, jasne. Moja pomyłka wzięła się stąd, że myślałem, że nazwa encji odnosi się po prostu do faktu, że to generacja minus pobór (ponieważ siłą rzeczy wynik jest taki sam niezależnie, czy by to liczyć na danych zbilansowanych czy nie). Tak czy inaczej, udało mi się wszystko ustawić i mam poprawną wartość energii zmagazynowanej w sieci. Wielkie dzięki za pomoc i za samą integrację!



Cześć. Świeżo postawiłem integrację i działa ona swietnie. Nie ukrywam ze chciałbym dostawić informacje o aktualnym stanie magazynu jako stary prosument:). Czy mogę prosić o kod? Nie ukrywam, że trochę to dla mnie zagmatwane jak czytam informacje odnośnie tego :)

**Comment by tomasz-soltysik** [comment]
> > Ok, jasne. Moja pomyłka wzięła się stąd, że myślałem, że nazwa encji odnosi się po prostu do faktu, że to generacja minus pobór (ponieważ siłą rzeczy wynik jest taki sam niezależnie, czy by to liczyć na danych zbilansowanych czy nie). Tak czy inaczej, udało mi się wszystko ustawić i mam poprawną wartość energii zmagazynowanej w sieci. Wielkie dzięki za pomoc i za samą integrację!
> 
> Cześć. Świeżo postawiłem integrację i działa ona swietnie. Nie ukrywam ze chciałbym dostawić informacje o aktualnym stanie magazynu jako stary prosument:). Czy mogę prosić o kod? Nie ukrywam, że trochę to dla mnie zagmatwane jak czytam informacje odnośnie tego :)

https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/206#issuecomment-3063743961 - tam opisałem jak dodać pomocnika. użyj tego drugiego szablonu i tylko podmień `<numerek>` na ten który znajdziesz u siebie na dowolnej encji tej integracji.

**Comment by jesiakdawid** [comment]
z tym liczeniem to chyba nie jest tak do końca jak mówicie już tłumacze configurable_energy_generation od tego trzeba odjąć 20% do 10KW lub 30% pow. 10KW dopiero od tego wyniku należy odjąć configurable_energy_consumption i mamy wynik ile nam zostało energii dodatkowo porównałem moje wartości po bilansowaniu i żadna z 17 encji nie pokazuje wartości jakie są na elicznik

**Comment by endriu4321** [comment]
Witam
Mam rozliczenie roczne jako prosument ale od maja do maja, czy da się zrobić template do "Tauron energy bank" ale tak żeby liczyło mi właśnie z tego okresu a nie wg. roku kalendarzowego ?

**Comment by adakca** [comment]
Panowie, myśle, że w tej dyskusji mylone są pojęcia. Przyjmijmy, że:
BALANS - to jest obliczenie różnicy pomiędzy energią oddaną a pobraną dla jakiegoś okresu.
BANK - to balans z uwzględnieniem 0.8 lub 0.7
BILANS(owanie) - to wektorowe, godzinowe  zbilansowanie energii pobranej i oddanej dla 3 faz.
I teraz co istotne, wszelkie rozliczenia (czy to Net billing cu Net metering) robione są wg tych zbilansowanych danych. W aplikacji eLicznik widoczne pod zakładkami energia po zbilansowaniu. Te dane dostępne są tylko i wyłącznie u dostawcy, nie ma możliwości ich wyliczenia samodzielnie (tak długo jak nie mówimy o czytaniu danych z licznika bezpośrednio i stale).
Niestety żadna z encji nie pokazuje tych danych. I tutaj prośba do twórcy integracji o pochylenie się nad tym. Tylko dane po zbilansowaniu pozwalają dokładnie wyliczyć bank lub skalkulować rozliczenie.
U mnie różnica (dane przed i po zbilansowaniu) jest rzędu 100 kWh rocznie (instalacja 9 kW).

**Comment by Landiss** [comment]
> Te dane dostępne są tylko i wyłącznie u dostawcy, nie ma możliwości ich wyliczenia samodzielnie (tak długo jak nie mówimy o czytaniu danych z licznika bezpośrednio i stale). Niestety żadna z encji nie pokazuje tych danych. I tutaj prośba do twórcy integracji o pochylenie się nad tym. Tylko dane po zbilansowaniu pozwalają dokładnie wyliczyć bank lub skalkulować rozliczenie. U mnie różnica (dane przed i po zbilansowaniu) jest rzędu 100 kWh rocznie (instalacja 9 kW).

To nie jest prawda. Cały ten wątek jest o tych danych. One są podane w atrybutach encji balanced. Ja sobie wyliczam stan magazynu tak:


```
#Magazyn Energii w sieci
input_number:
  initial_energy_bank:
    min: 0
    max: 100000000
    step: 1
    mode: box
template:
  - sensor:
      - name: "Magazyn Energii Tauron"
        state_class: total
        device_class: energy
        unique_id: magazyn_energii_tauron
        icon: mdi:home-battery-outline
        #atrybut sum_generation jest podany jako negatywna wartość, dlatego jest odejmowany poniżej
        state: "{{ (states('input_number.initial_energy_bank') | float(0) - state_attr('sensor.tauron_amiplus_tutajnumer_configurable_balance', 'sum_generation') | float(0) * 0.8 - state_attr('sensor.tauron_amiplus_tutajnumer_configurable_balance', 'sum_consumption') | float(0)) | round() }}"
        unit_of_measurement: "kWh"
        availability: "{{ state_attr('sensor.tauron_amiplus_znowunumer_configurable_balance', 'sum_generation') | is_number and state_attr('sensor.tauron_amiplus_znowunumer_configurable_balance', 'sum_consumption') | is_number }}"

```

Co istotne, używam configurable balance z początkiem ustawionym na początek obecnego okresu rozliczeniowego (trzeba zmieniać jak się kończy okres, chyba się tego nie da zautomatyzować,a przynajmniej jak nie umiem).
